# Generated by Django 4.1.2 on 2022-10-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=100)),
                ('RegNumber', models.IntegerField(blank=True, default=None, null=True)),
                ('Email', models.EmailField(default=None, max_length=100)),
                ('Mob', models.CharField(default=None, max_length=13)),
                ('Semester', models.IntegerField(default=None)),
                ('Photo', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
